################################
# Base game params
################################

GAME_PARAMS:

  DISPLAY_SIZE: [600, 480]
  BACKGROUND_COLOR: '#111111'

################################
# Params for all enemies
################################

ENEMY_PARAMS:

  ENEMIES:

    SMALL:
      ANIMATIONS:
        - 'images/enemy_small_1.gif'
        - 'images/enemy_small_2.gif'
      SIZE: [16, 16]

    MEDIUM:
      ANIMATIONS:
        - 'images/enemy_medium_1.gif'
        - 'images/enemy_medium_2.gif'
      SIZE: [22, 16]

    HUGE:
      ANIMATIONS:
        - 'images/enemy_huge_1.gif'
        - 'images/enemy_huge_2.gif'
      SIZE: [24, 16]
      POINTS: 10

    DEAD:
      ANIMATIONS: 'images/enemy_dead.gif'
      SIZE: [26, 16]

    UFO:
      ANIMATIONS: 'images/enemy_ufo.gif'
      SIZE: [48, 21]

################################
# Params for platforms
################################

PLATFORM_PARAMS:

  ANIMATIONS:
    - 'images/bunker.gif'
  SIZE: [44, 32]

################################
# Player params
################################

PLAYER_PARAMS:

  ANIMATIONS: 'images/player.gif'
  ANIMATIONS_DEATH: 'images/player_dead.gif'
  SIZE: [26, 16]
