################################
# Base game params
################################

GAME_PARAMS:

  DISPLAY_SIZE: [600, 480]
  BACKGROUND_COLOR: '#222222'
  TICK_RATE: 60
  MAX_WAVE: 3

################################
# Params for all enemies
################################

ENEMY_PARAMS:

  ENEMIES:

    SMALL:
      ANIMATIONS:
        - 'images/enemy_small_1.gif'
        - 'images/enemy_small_2.gif'
      SIZE: [16, 16]
      POINTS: 30

    MEDIUM:
      ANIMATIONS:
        - 'images/enemy_medium_1.gif'
        - 'images/enemy_medium_2.gif'
      SIZE: [22, 16]
      POINTS: 20

    HUGE:
      ANIMATIONS:
        - 'images/enemy_huge_1.gif'
        - 'images/enemy_huge_2.gif'
      SIZE: [24, 16]
      POINTS: 10

    DEAD:
      ANIMATIONS: 'images/enemy_dead.gif'
      SIZE: [26, 16]

    UFO:
      ANIMATIONS: 'images/enemy_ufo.gif'
      SIZE: [48, 21]
      POINTS: 100

  HEALTH: 50
  STEP_X: 10
  STEP_Y: 20
  BULLET_SPEED: 5
  BULLET_STRENGTH: 50
  BASE_SPEED: 1
  MAX_SPEED: 10
  SHOOT_PROBABILITY: 0.01
  UFO_PROBABILITY: 0.001
  UFO_SPEED: 5
  MAX_Y: 300

################################
# Params for platforms
################################

PLATFORM_PARAMS:

  ANIMATIONS:
    - 'images/bunker.gif'
  SIZE: [44, 32]
  HEALTH: 200
  Y_POSITION: 350

################################
# Player params
################################

PLAYER_PARAMS:

  ANIMATIONS: 'images/player.gif'
  ANIMATIONS_DEATH: 'images/player_dead.gif'
  SIZE: [26, 16]
  SHOOT_DELAY: 0.05
  SPEED: 10
  HEALTH: 50
  BULLET_SPEED: 10
  BULLET_STRENGTH: 50
  LIVES: 3
