#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER "$APP_USER" WITH PASSWORD '$APP_USER_PASSWORD';
    CREATE DATABASE "$APP_DATABASE";
    GRANT ALL PRIVILEGES ON DATABASE "$APP_DATABASE" TO "$APP_USER";
EOSQL
