---
# base docker-compose configuration
version: '2'

volumes:
  "jenkins-home":
    external:
      name: infra_jenkins-home

services:
  jenkins:
    build:
      context: .
    container_name: infra_jenkins
    ports:
      - "8080:8080"
    volumes:
      - "jenkins-home:/var/jenkins_home/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/jenkins-container-tmp:/tmp"
    restart: unless-stopped
